# Generated by Django 5.0.6 on 2024-07-04 12:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_users_auth_provider"),
    ]

    operations = [
        migrations.AlterField(
            model_name="academy",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="academy_user",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
