# Generated by Django 5.0.6 on 2024-09-12 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_time', '0003_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('message', 'Message'), ('friend_request', 'Friend Request'), ('friend_request_accept', 'Friend Request Accepted'), ('follow', 'Follow'), ('new_post', 'New Post'), ('new_trial', 'New Trial')], max_length=50, null=True),
        ),
    ]
