# Generated by Django 5.0.6 on 2024-06-21 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_profile", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="useracademy",
            name="end_year",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
