# Generated by Django 5.0.6 on 2024-06-23 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_useracademy_end_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='useracademy',
            name='sport',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
