# Generated by Django 5.0.6 on 2024-07-04 12:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PlayersInTrial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("status", models.CharField(blank=True, max_length=200, null=True)),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                ("dob", models.DateField(blank=True, null=True)),
                ("number", models.CharField(blank=True, max_length=30, null=True)),
                ("email", models.EmailField(blank=True, max_length=200, null=True)),
                ("state", models.CharField(blank=True, max_length=100, null=True)),
                ("district", models.CharField(blank=True, max_length=100, null=True)),
                ("unique_id", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "achievement",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="player",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PlayersInTrialDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "requirement",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("value", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "player_trial",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="playersintrial",
                        to="selection_trial.playersintrial",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Trial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("sport", models.CharField(blank=True, max_length=50, null=True)),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                ("state", models.CharField(blank=True, max_length=100, null=True)),
                ("district", models.CharField(blank=True, max_length=100, null=True)),
                ("location", models.CharField(blank=True, max_length=200, null=True)),
                ("venue", models.CharField(blank=True, max_length=255, null=True)),
                ("trial_date", models.DateField(blank=True, null=True)),
                ("trial_time", models.TimeField(blank=True, null=True)),
                ("is_participant_limit", models.BooleanField(default=False)),
                ("total_participant_limit", models.IntegerField(blank=True, null=True)),
                ("is_registration_fee", models.BooleanField(default=True)),
                ("registration_fee", models.IntegerField(blank=True, null=True)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="images/"),
                ),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "academy",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="academy",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="playersintrial",
            name="trial",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="trial",
                to="selection_trial.trial",
            ),
        ),
        migrations.CreateModel(
            name="TrialRequirement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "requirement",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "trial",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trial_detials",
                        to="selection_trial.trial",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
